server:
  port: 8080

logging:
  level:
    io:
      kimmking:
        cache : info

# 作业，在这里使用spring boot配置各项内容，
spring:
  redis:
    sentinel:
      master: mymaster
      nodes: 192.168.50.244:26379,192.168.50.244:26380
    password: 123456
